import type { PaperProfile, Paragraph, Sentence } from '../types';
export function findContext(profile:PaperProfile, selected:string){
 const norm=(s:string)=>s.replace(/\s+/g,' ').trim().toLowerCase(); const q=norm(selected); const paras=profile.sections.flatMap(s=>s.paragraphs);
 let para=paras.find(p=>norm(p.text).includes(q)); if(!para){const words=new Set(q.split(/\W+/));para=paras.map(p=>({p,score:norm(p.text).split(/\W+/).filter(w=>words.has(w)).length})).sort((a,b)=>b.score-a.score)[0]?.p;}
 para ||= paras[0]; const sec=profile.sections.find(s=>s.id===para?.sectionId)||profile.sections[0]; const pi=paras.indexOf(para); const sentence=para.sentences.find(s=>norm(s.text).includes(q)||q.includes(norm(s.text)))||closestSentence(para.sentences,q);
 const related=retrieve(profile,selected,3).filter(p=>p.id!==para.id);
 return {sentence,paragraph:para,section:sec,previousParagraph:paras[pi-1],nextParagraph:paras[pi+1],related};
}
function closestSentence(ss:Sentence[],q:string){const ws=new Set(q.split(/\W+/));return ss.map(s=>({s,n:s.text.toLowerCase().split(/\W+/).filter(w=>ws.has(w)).length})).sort((a,b)=>b.n-a.n)[0]?.s;}
export function retrieve(profile:PaperProfile,q:string,k=4){const terms=q.toLowerCase().split(/[^\p{L}\p{N}]+/u).filter(x=>x.length>2);return profile.sections.flatMap(s=>s.paragraphs).map(p=>({p,score:terms.reduce((n,t)=>n+(p.text.toLowerCase().includes(t)?1:0),0)})).sort((a,b)=>b.score-a.score).slice(0,k).map(x=>x.p);}
export function completeSelection(profile:PaperProfile,selected:string){const raw=selected.replace(/\s+/g,' ').trim();if(raw.length<=12||(raw.match(/[.!?。！？]/g)||[]).length>1)return raw;const compact=(s:string)=>s.toLowerCase().replace(/[^\p{L}\p{N}]+/gu,'');const q=compact(raw),all=profile.sections.flatMap(s=>s.paragraphs).flatMap(p=>p.sentences);const grams=(s:string)=>new Set(Array.from({length:Math.max(0,s.length-1)},(_,i)=>s.slice(i,i+2)));const qg=grams(q);let best:{text:string;score:number}|undefined;for(const sentence of all){const t=compact(sentence.text);let score=t.includes(q)?1:q.includes(t)?0.95:0;if(!score&&qg.size){const tg=grams(t);score=[...qg].filter(x=>tg.has(x)).length/qg.size}if(!best||score>best.score)best={text:sentence.text,score}}const candidate=best?.text.replace(/\s+/g,' ').trim();if(!candidate||best!.score<.58||candidate.length>Math.max(700,raw.length*5))return raw;return candidate;}
export function buildPrompt(profile:PaperProfile,selected:string,history:{role:string;content:string}[]=[]){const c=findContext(profile,selected),cut=(s:string|undefined,n:number)=>(s||'').slice(0,n);return {context:c,messages:[{role:'system',content:`你是严谨的论文导师。只依据所给论文上下文回答；外部知识必须标为【辅助理解】，证据不足必须说“仅根据当前论文无法确定”。简洁输出六个小标题：一句话解释、具体例子、为什么作者这里要写、这一段在讲什么、这一节在讲什么、导师阅读建议。论文研究问题：${cut(profile.researchQuestion,500)}\n核心贡献：${cut(profile.contributions.join('; '),800)}`},{role:'user',content:`选中文字：${cut(selected,800)}\n完整句：${cut(c.sentence?.text,1200)}\n当前段落：${cut(c.paragraph?.text,2400)}\n上一段：${cut(c.previousParagraph?.text,1000)}\n下一段：${cut(c.nextParagraph?.text,1000)}\n章节：${c.section?.title}\n章节摘要：${cut(c.section?.summary,1200)}\n相关内容：${c.related.map(p=>`[第${p.page}页] ${cut(p.text,700)}`).join('\n')}`},...history.slice(-4)]};}
export function localExplanation(profile:PaperProfile,selected:string){const c=findContext(profile,selected);return `## 一句话解释\n${plain(selected)}\n\n## 具体例子\n把作者的说法想成一个具体输入到输出的过程：输入是论文当前讨论的对象，经过“${c.section?.title||'当前方法'}”中的处理，得到可用于判断或预测的表示。若涉及实体对齐，可以把“北京 —首都属于→ 中国”和“Beijing —capitalOf→ China”看作两种语言下的对应结构；模型利用实体及关系线索判断二者是否指向同一对象。\n\n## 为什么作者这里要写\n这句话在段落中主要承担“${c.paragraph?.role||'展开论证'}”的作用，承接前文并为后续说明铺垫。\n\n## 这一段在讲什么\n${c.paragraph?.text.slice(0,460)||'仅根据当前提取结果无法确定。'}\n\n## 这一节在讲什么\n**${c.section?.title||'未识别章节'}** 主要围绕：${c.section?.summary.slice(0,420)||'仅根据当前论文无法确定。'}\n\n## 导师阅读建议\n先抓住这句话的输入、处理过程与输出，再判断它是核心机制还是过渡说明。当前最值得掌握的是它与论文研究问题“${profile.researchQuestion.slice(0,180)}”之间的联系。\n\n> 本回答由本地结构化上下文生成。配置模型后可获得更深入解释。`}
function plain(t:string){const s=t.replace(/\s+/g,' ').trim();return s.length>220?s.slice(0,217)+'…':`作者在这里强调：${s}`;}
