import{useState}from'react';
import{Copy,Info,X}from'@phosphor-icons/react';
import type{AiCallRecord}from'./services/aiObservability';
import{safeCopyText}from'./services/aiObservability';
const tokens=(n?:number)=>n==null?'不可用':n.toLocaleString();
const seconds=(n:number)=>`${(n/1000).toFixed(n<1000?2:1)} s`;
export function AiCallDetails({call}:{call:AiCallRecord}){const[open,setOpen]=useState(false),[copied,setCopied]=useState('');const copy=async(label:string,value:unknown)=>{await navigator.clipboard.writeText(typeof value==='string'?value:safeCopyText(value));setCopied(label);setTimeout(()=>setCopied(''),1200)};return <div className="call-details"><details><summary><Info/>{call.model} · {call.callType} · {call.usage.totalTokens==null?'Token 不可用':`${tokens(call.usage.totalTokens)} tokens`} · {seconds(call.latencyMs)} · {call.estimatedCost==null?'费用未配置':`约 ¥${call.estimatedCost.toFixed(4)}`}</summary><div className="call-metrics"><span>输入<strong>{tokens(call.usage.inputTokens)}</strong></span><span>输出<strong>{tokens(call.usage.outputTokens)}</strong></span><span>总计<strong>{tokens(call.usage.totalTokens)}</strong></span><span>总耗时<strong>{seconds(call.latencyMs)}</strong></span>{call.ttftMs!=null&&<span>首字延迟<strong>{seconds(call.ttftMs)}</strong></span>}<span>本地缓存<strong>{call.localCacheHit?'命中':'未命中'}</strong></span><span>服务商缓存<strong>{call.providerCacheHit==null?'不可用':call.providerCacheHit?'命中':'未命中'}</strong></span><span>估算费用<strong>{call.estimatedCost==null?'未配置':`¥${call.estimatedCost.toFixed(6)}`}</strong></span></div><button onClick={()=>setOpen(true)}>查看本次实际上下文</button></details>{open&&<div className="context-modal" role="dialog" aria-label="请求上下文查看器"><section><header><div><small>{call.callType} · {call.model}</small><h2>本次请求详情</h2><p>Request ID：{call.requestId}</p></div><button aria-label="关闭上下文查看器" onClick={()=>setOpen(false)}><X/></button></header><div className="context-scroll"><Part title="用户选区" value={call.snapshot.selection} onCopy={()=>copy('选区',call.snapshot.selection)} copied={copied==='选区'}/><Part title="本次用户问题" value={call.snapshot.userQuestion||'未使用'} onCopy={()=>copy('问题',call.snapshot.userQuestion||'未使用')} copied={copied==='问题'}/><Part title="对话阅读状态" value={call.snapshot.conversationState||'未使用'}/>{call.snapshot.image&&<Part title="图片附件" value={`已附加\nMIME：${call.snapshot.image.mime}\n尺寸：${call.snapshot.image.width&&call.snapshot.image.height?`${call.snapshot.image.width} × ${call.snapshot.image.height}`:'不可用'}\n页码：${call.snapshot.image.page??'不可用'}\nBase64：已隐藏`}/>}<div className="context-groups">{call.snapshot.sections.map((part,i)=><details key={`${part.name}-${i}`}><summary>{part.sourceType}<small>{part.reason||part.name}{part.page?` · p.${part.page}`:''}{part.section?` · ${part.section}`:''}{part.paragraphId?` · ${part.paragraphId}`:''}{part.score!=null?` · score ${part.score.toFixed(2)}`:''}</small></summary><pre>{clip(part.content)}</pre><button onClick={()=>copy(`${part.name}-${i}`,part.content)}><Copy/>{copied===`${part.name}-${i}`?'已复制':'复制当前部分'}</button></details>)}</div><Part title="最终实际 messages（已安全清洗）" value={safeCopyText(call.snapshot.finalMessages)} onCopy={()=>copy('messages',call.snapshot.finalMessages)} copied={copied==='messages'}/></div></section></div>}</div>}
const clip=(s:string)=>s.length>12000?`${s.slice(0,12000)}\n…已折叠其余内容`:s;
function Part({title,value,onCopy,copied=false}:{title:string;value:string;onCopy?:()=>void;copied?:boolean}){return <details className="context-part"><summary>{title}</summary><pre>{clip(value)}</pre>{onCopy&&<button onClick={onCopy}><Copy/>{copied?'已复制':'复制当前部分'}</button>}</details>}
